apiVersion: apps/v1
kind: Deployment
metadata: 
 name: helloworld-deployment
spec: 
 replicas: 1
 selector:
  matchLabels:
   app: hello-world
 template:
  metadata:
    labels:
      app: hello-world
  spec:
    containers:
    - name: hello-world
      image: paulbouwer/hello-kubernetes:1.10.1
      ports:
      - containerPort: 8080
        
